// Regenerates the branch portal's browser-global copies of modules shared with the shop-admin app, so both
// portals read supplier files, print labels and match scans the same way. Run after editing a source file:
//   node scripts/sync-shared.js
const fs = require('fs');
const path = require('path');

const SHOP_ADMIN = path.resolve(__dirname, '../../infinest-frontend/src/components/shop-admin/sales');

const MODULES = [
  {
    source: 'inventoryImport.js',
    target: 'src/utils/inventoryImport.js',
    global: 'InventoryImport',
    needs: 'Needs the SheetJS global (window.XLSX) loaded before this script.',
    replace: [['import * as XLSX from "xlsx";', 'var XLSX = window.XLSX;']],
  },
  {
    source: 'barcodeLabels.js',
    target: 'src/utils/barcodeLabels.js',
    global: 'BarcodeLabels',
    needs: 'jsPDF and JsBarcode are passed in by the caller.',
    replace: [],
  },
];

for (const m of MODULES) {
  const sourcePath = path.join(SHOP_ADMIN, m.source);
  const targetPath = path.resolve(__dirname, '..', m.target);
  let body = fs.readFileSync(sourcePath, 'utf8');
  if (!body.trim()) throw new Error('Source is empty: ' + sourcePath);
  for (const [from, to] of m.replace) body = body.replace(from, to);

  const names = [...body.matchAll(/^export (?:async function|function|const|let) (\w+)/gm)].map((x) => x[1]);
  body = body.replace(/^export (async function|function|const|let) /gm, '$1 ');
  if (/^\s*(import|export)\b/m.test(body)) throw new Error('Unconverted import/export in ' + sourcePath);

  const out = `// GENERATED by scripts/sync-shared.js from
// infinest-frontend/src/components/shop-admin/sales/${m.source} — edit that file, then re-run the script.
// ${m.needs}
(function () {
${body.trim()}

window.${m.global} = { ${names.join(', ')} };
})();
`;
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, out);
  console.log(`Wrote ${m.target} → window.${m.global} (${names.length}: ${names.join(', ')})`);
}
