// GENERATED by scripts/sync-shared.js from
// infinest-frontend/src/components/shop-admin/sales/barcodeLabels.js — edit that file, then re-run the script.
// jsPDF and JsBarcode are passed in by the caller.
(function () {
// Shared barcode label + scan helpers for the shop-admin and branch portals.
// No imports: jsPDF, JsBarcode and document are passed in, so this one file works as an ES module (shop-admin)
// and as a browser global (branch copy generated by sales-frontend/scripts/sync-shared.js — do not edit that copy).

const DOT_MM = 25.4 / 203;          // one dot of a 203 DPI thermal printer
const PT_MM = 25.4 / 72;
const PADDING_MM = 1.5;
const QUIET_ZONE_MM = 2;            // clear space left/right of the bars, measured from the label edge
const MIN_MODULE_DOTS = 2;          // narrowest bar 2 dots = 0.25 mm
const MAX_MODULE_DOTS = 4;
const CANVAS_MODULE_PX = 3;
const CANVAS_HEIGHT_PX = 80;
const MIN_BAR_HEIGHT_MM = 5;
const LINE_SPACING = 1.15;
const GAP_MM = 0.5;
const MIN_CODE_FONT_PT = 4;

// Tried in order: text only shrinks when the bars would otherwise get too short to scan
const TEXT_LEVELS = [
  { shop: 6, product: 7, productLines: 2, code: 6 },
  { shop: 5, product: 6, productLines: 2, code: 5 },
  { shop: 5, product: 6, productLines: 1, code: 5 },
  { shop: 0, product: 5, productLines: 1, code: 5 },
];

const THERMAL_DEFAULTS = { widthMm: 50, heightMm: 25, showTypeTag: false };
const THERMAL_LIMITS = { minWidthMm: 20, maxWidthMm: 110, minHeightMm: 12, maxHeightMm: 150 };
const STORAGE_KEY = 'barcodeLabels.thermal';

// ── Settings ──────────────────────────────────────────────────────────────────

const inRange = (v, min, max) => Number.isFinite(Number(v)) && Number(v) >= min && Number(v) <= max;

function thermalSizeError(widthMm, heightMm) {
  const L = THERMAL_LIMITS;
  if (!inRange(widthMm, L.minWidthMm, L.maxWidthMm)) return `Label width must be ${L.minWidthMm}–${L.maxWidthMm} mm`;
  if (!inRange(heightMm, L.minHeightMm, L.maxHeightMm)) return `Label height must be ${L.minHeightMm}–${L.maxHeightMm} mm`;
  return null;
}

function loadThermalSettings() {
  const out = { ...THERMAL_DEFAULTS };
  try {
    const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || '{}');
    if (!thermalSizeError(saved.widthMm, saved.heightMm)) {
      out.widthMm = Number(saved.widthMm);
      out.heightMm = Number(saved.heightMm);
    }
    out.showTypeTag = saved.showTypeTag === true;
  } catch (_) { /* storage unavailable or corrupt: use defaults */ }
  return out;
}

function saveThermalSettings(settings) {
  if (thermalSizeError(settings.widthMm, settings.heightMm)) return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify({
      widthMm: Number(settings.widthMm),
      heightMm: Number(settings.heightMm),
      showTypeTag: !!settings.showTypeTag,
    }));
  } catch (_) { /* ignore */ }
}

// ── Scan matching ─────────────────────────────────────────────────────────────

function normalizeScanCode(value) {
  return String(value == null ? '' : value).toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Resolves a scanned or typed code. `groups` are candidate lists in priority order, each item { code, value }.
 * Exact (case-insensitive) matches win. Otherwise codes are compared with spaces, hyphens and other symbols
 * removed, because labels printed before the scan fix encoded "POR 2203" as "POR2203".
 * Returns { value, group }, { ambiguous: true } when the loose match hits different codes, or null.
 */
function findScanMatch(scanned, groups) {
  const exact = String(scanned == null ? '' : scanned).trim().toLowerCase();
  if (!exact) return null;
  for (let g = 0; g < groups.length; g++) {
    const hit = groups[g].find((c) => String(c.code == null ? '' : c.code).trim().toLowerCase() === exact);
    if (hit) return { value: hit.value, group: g };
  }
  const loose = normalizeScanCode(exact);
  if (!loose) return null;
  for (let g = 0; g < groups.length; g++) {
    const hits = groups[g].filter((c) => normalizeScanCode(c.code) === loose);
    if (!hits.length) continue;
    const codes = new Set(hits.map((c) => String(c.code).trim().toLowerCase()));
    if (codes.size > 1) return { ambiguous: true, group: g };
    return { value: hits[0].value, group: g };
  }
  return null;
}

/**
 * POS add-by-scan over branch stock rows: IMEIs first (phones carry one barcode per IMEI), then product numbers.
 * Returns { product, imei, byProductNo } or { ambiguous: true } or null.
 */
function resolvePosScan(products, scanned) {
  const imeisOf = (p) => (Array.isArray(p.centralOnlyImes) && p.centralOnlyImes.length ? p.centralOnlyImes
    : Array.isArray(p.centralImes) && p.centralImes.length ? p.centralImes
      : Array.isArray(p.imes) ? p.imes : []);
  const imeiCandidates = [];
  const productCandidates = [];
  (products || []).forEach((p) => {
    imeisOf(p).forEach((imei) => { if (imei) imeiCandidates.push({ code: imei, value: { product: p, imei } }); });
    if (p.productNo) productCandidates.push({ code: p.productNo, value: { product: p, imei: null } });
  });
  const hit = findScanMatch(scanned, [imeiCandidates, productCandidates]);
  if (!hit) return null;
  if (hit.ambiguous) return { ambiguous: true };
  return { product: hit.value.product, imei: hit.value.imei, byProductNo: hit.group === 1 };
}

// ── Thermal labels ────────────────────────────────────────────────────────────

const barcodeValueOf = (item) => String(item && item.barcodeValue != null ? item.barcodeValue : '').trim();

const lineMm = (pt) => pt * PT_MM * LINE_SPACING;

function applyFont(doc, pt, bold) {
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setFontSize(pt);
}

function ellipsize(doc, text, maxWidth) {
  const s = String(text || '');
  if (doc.getTextWidth(s) <= maxWidth) return s;
  let lo = 0;
  let hi = s.length;
  while (lo < hi) {
    const mid = Math.ceil((lo + hi) / 2);
    if (doc.getTextWidth(s.slice(0, mid).trimEnd() + '...') <= maxWidth) lo = mid;
    else hi = mid - 1;
  }
  return s.slice(0, lo).trimEnd() + '...';
}

function wrapLines(doc, text, maxWidth, maxLines) {
  const lines = doc.splitTextToSize(String(text || ''), maxWidth).map((l) => (doc.getTextWidth(l) > maxWidth ? ellipsize(doc, l, maxWidth) : l));
  if (lines.length <= maxLines) return lines;
  const kept = lines.slice(0, maxLines - 1);
  kept.push(ellipsize(doc, lines.slice(maxLines - 1).join(' '), maxWidth));
  return kept;
}

/** Code 128 module count for a value, or null if it cannot be encoded. */
function countModules(JsBarcode, value) {
  if (!value) return null;
  try {
    const data = {};
    JsBarcode(data, value, { format: 'CODE128' });
    const n = (data.encodings || []).reduce((sum, e) => sum + String(e.data || '').length, 0);
    return n > 0 ? n : null;
  } catch (_) {
    return null;
  }
}

function layoutText(doc, label, settings, lvl, textW) {
  const t = { fonts: {}, lines: { shop: null, product: [], code: label.code, tag: null }, topH: 0, bottomH: 0, codeFits: true };
  if (label.shopName && lvl.shop) {
    applyFont(doc, lvl.shop, false);
    t.fonts.shop = lvl.shop;
    t.lines.shop = ellipsize(doc, label.shopName, textW);
    t.topH += lineMm(lvl.shop);
  }
  applyFont(doc, lvl.product, true);
  t.fonts.product = lvl.product;
  t.lines.product = wrapLines(doc, label.productName, textW, lvl.productLines);
  t.topH += t.lines.product.length * lineMm(lvl.product);

  let codePt = lvl.code;
  applyFont(doc, codePt, false);
  while (codePt > MIN_CODE_FONT_PT && doc.getTextWidth(label.code) > textW) {
    codePt -= 0.5;
    applyFont(doc, codePt, false);
  }
  t.fonts.code = codePt;
  t.codeFits = doc.getTextWidth(label.code) <= textW;
  t.bottomH += lineMm(codePt);

  if (settings.showTypeTag && label.type) {
    t.fonts.tag = Math.min(codePt, 5);
    t.lines.tag = label.type;
    t.bottomH += lineMm(t.fonts.tag);
  }
  return t;
}

/**
 * Lays out one thermal label: text sizes and positions, and a barcode whose module is a whole number of
 * printer dots (so every bar prints at an exact width) and at least 0.25 mm wide whenever the label allows.
 */
function planThermalLabel(doc, label, settings, modules) {
  const W = Number(settings.widthMm);
  const H = Number(settings.heightMm);
  const textW = W - 2 * PADDING_MM;
  const inset = Math.max(PADDING_MM, QUIET_ZONE_MM);
  const barMaxW = W - 2 * inset;
  const problems = [];

  let moduleMm = 0;
  let moduleDots = 0;
  if (!label.code || label.code === 'N/A') problems.push('product has no code');
  if (!modules) {
    if (label.code && label.code !== 'N/A') problems.push('code has characters a barcode cannot hold');
  } else {
    moduleDots = Math.min(MAX_MODULE_DOTS, Math.floor(barMaxW / (modules * DOT_MM) + 1e-9));
    moduleMm = moduleDots * DOT_MM;
    if (moduleDots < MIN_MODULE_DOTS) {
      moduleMm = barMaxW / modules;
      const needW = Math.ceil(modules * MIN_MODULE_DOTS * DOT_MM + 2 * inset);
      problems.push(`code too long for a ${W} mm wide label (needs at least ${needW} mm)`);
    }
  }

  let level = 0;
  let t = null;
  let barAvailH = 0;
  for (level = 0; level < TEXT_LEVELS.length; level++) {
    t = layoutText(doc, label, settings, TEXT_LEVELS[level], textW);
    barAvailH = H - 2 * PADDING_MM - t.topH - t.bottomH - 2 * GAP_MM;
    if (barAvailH >= MIN_BAR_HEIGHT_MM || !modules) break;
  }
  if (level === TEXT_LEVELS.length) level -= 1;
  if (modules && barAvailH < MIN_BAR_HEIGHT_MM) {
    problems.push(`label too short for scannable bars (${Math.max(0, barAvailH).toFixed(1)} mm left for the barcode)`);
  }
  if (!t.codeFits) problems.push('printed code text is wider than the label');

  // Aspect ratio is fixed by the canvas (modules × px wide, 80 px high), so bar height = module × 80 / px.
  let modulePx = CANVAS_MODULE_PX;
  let barW = 0;
  let barH = 0;
  if (modules) {
    barW = modules * moduleMm;
    barH = (moduleMm * CANVAS_HEIGHT_PX) / modulePx;
    if (barH > barAvailH) {
      modulePx = Math.max(CANVAS_MODULE_PX, Math.ceil((moduleMm * CANVAS_HEIGHT_PX) / Math.max(barAvailH, 0.5) - 1e-9));
      barH = (moduleMm * CANVAS_HEIGHT_PX) / modulePx;
    }
  }

  // Vertical: text block on top, then barcode + human-readable code centred in the remaining space
  const y = { shop: null, product: [], barcode: 0, code: 0, tag: null };
  let cursor = PADDING_MM;
  if (t.lines.shop) { y.shop = cursor; cursor += lineMm(t.fonts.shop); }
  t.lines.product.forEach(() => { y.product.push(cursor); cursor += lineMm(t.fonts.product); });
  const regionTop = cursor + GAP_MM;
  const regionH = H - PADDING_MM - regionTop;
  const groupH = (modules ? barH + GAP_MM : 0) + t.bottomH;
  const groupTop = regionTop + Math.max(0, (regionH - groupH) / 2);
  y.barcode = groupTop;
  y.code = groupTop + (modules ? barH + GAP_MM : 0);
  if (t.lines.tag) y.tag = y.code + lineMm(t.fonts.code);

  return {
    widthMm: W,
    heightMm: H,
    modules,
    moduleDots: moduleDots >= MIN_MODULE_DOTS ? moduleDots : null,
    moduleMm,
    modulePx,
    barcode: { x: (W - barW) / 2, y: y.barcode, w: barW, h: barH },
    fonts: t.fonts,
    lines: t.lines,
    y,
    reducedText: level > 0,
    problems,
  };
}

function toThermalLabel(item, shopName) {
  return {
    code: barcodeValueOf(item),
    productName: item.productName || '',
    type: item.type || '',
    shopName: shopName || '',
  };
}

const labelKey = (item) => `${barcodeValueOf(item)}\u0000${item.productName || ''}\u0000${item.type || ''}`;

/**
 * Checks every distinct label without building the PDF. Returns
 * { problems: [{ code, productName, count, problems }], reducedText: <labels using smaller text> }.
 */
function checkThermalLabels({ jsPDF, JsBarcode, labels, settings, shopName }) {
  const result = { problems: [], reducedText: 0 };
  if (!labels.length || thermalSizeError(settings.widthMm, settings.heightMm)) return result;
  const doc = new jsPDF({ unit: 'mm', format: [settings.widthMm, settings.heightMm], orientation: settings.widthMm >= settings.heightMm ? 'landscape' : 'portrait' });
  const seen = new Map();
  labels.forEach((item) => {
    const key = labelKey(item);
    if (seen.has(key)) { seen.get(key).count += 1; return; }
    const label = toThermalLabel(item, shopName);
    const plan = planThermalLabel(doc, label, settings, countModules(JsBarcode, label.code));
    const entry = { code: label.code, productName: label.productName, count: 1, plan };
    seen.set(key, entry);
  });
  seen.forEach((entry) => {
    if (entry.plan.problems.length) result.problems.push({ code: entry.code, productName: entry.productName, count: entry.count, problems: entry.plan.problems });
    if (entry.plan.reducedText) result.reducedText += entry.count;
  });
  return result;
}

function drawThermalLabel(doc, plan, image) {
  const cx = plan.widthMm / 2;
  const opts = { align: 'center', baseline: 'top' };
  doc.setTextColor(0, 0, 0);
  if (plan.lines.shop) {
    applyFont(doc, plan.fonts.shop, false);
    doc.text(plan.lines.shop, cx, plan.y.shop, opts);
  }
  applyFont(doc, plan.fonts.product, true);
  plan.lines.product.forEach((line, i) => doc.text(line, cx, plan.y.product[i], opts));
  if (image) {
    // Height comes from the canvas aspect ratio, never a fixed box. 'FAST' = Flate: jsPDF stores PNGs uncompressed otherwise
    const w = plan.barcode.w;
    const h = (w * image.height) / image.width;
    doc.addImage(image.dataUrl, 'PNG', plan.barcode.x, plan.barcode.y, w, h, image.alias, 'FAST');
  }
  applyFont(doc, plan.fonts.code, false);
  doc.text(plan.lines.code, cx, plan.y.code, opts);
  if (plan.lines.tag) {
    applyFont(doc, plan.fonts.tag, true);
    doc.text(plan.lines.tag, cx, plan.y.tag, opts);
  }
}

/** One PDF page per label, each page exactly widthMm × heightMm. Returns the jsPDF document. */
function buildThermalPdf({ jsPDF, JsBarcode, document: dom, labels, settings, shopName }) {
  const W = Number(settings.widthMm);
  const H = Number(settings.heightMm);
  const orientation = W >= H ? 'landscape' : 'portrait';
  const doc = new jsPDF({ orientation, unit: 'mm', format: [W, H] });
  const plans = new Map();
  const images = new Map();

  labels.forEach((item, i) => {
    if (i > 0) doc.addPage([W, H], orientation);
    const key = labelKey(item);
    if (!plans.has(key)) {
      const label = toThermalLabel(item, shopName);
      plans.set(key, planThermalLabel(doc, label, settings, countModules(JsBarcode, label.code)));
    }
    const plan = plans.get(key);
    let image = null;
    if (plan.modules) {
      const imgKey = `${plan.modulePx}\u0000${plan.lines.code}`;
      if (!images.has(imgKey)) {
        const canvas = dom.createElement('canvas');
        JsBarcode(canvas, plan.lines.code, {
          format: 'CODE128',
          width: plan.modulePx,
          height: CANVAS_HEIGHT_PX,
          margin: 0,
          displayValue: false,
          background: '#ffffff',
          lineColor: '#000000',
        });
        images.set(imgKey, { dataUrl: canvas.toDataURL('image/png'), width: canvas.width, height: canvas.height, alias: `bc${images.size}` });
      }
      image = images.get(imgKey);
    }
    drawThermalLabel(doc, plan, image);
  });
  return doc;
}

// ── A4 sheet (original layout, unchanged) ─────────────────────────────────────

/**
 * A4 portrait, 2 × 4 grid of 90 × 55 mm labels. getCanvas(i) returns the rendered preview barcode canvas
 * for labels[i]. Returns the jsPDF document.
 */
function buildA4Pdf({ jsPDF, labels, shopName, getCanvas }) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 10;
  const labelWidth = (pageWidth - margin * 3) / 2;
  const labelHeight = 55;
  const gap = 10;

  let x = margin;
  let y = margin;
  let labelCount = 0;

  for (let i = 0; i < labels.length; i++) {
    const item = labels[i];
    const canvas = getCanvas(i);

    if (canvas) {
      // Add new page if needed
      if (y + labelHeight > pageHeight - margin) {
        doc.addPage();
        x = margin;
        y = margin;
      }

      // Draw border
      doc.setDrawColor(200);
      doc.rect(x, y, labelWidth, labelHeight);

      // Shop name
      let topY = y;
      if (shopName) {
        doc.setFontSize(9);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(0);
        doc.text(doc.splitTextToSize(shopName, labelWidth - 4)[0], x + labelWidth / 2, y + 5, { align: 'center' });
        topY = y + 5;
      }

      // Product name
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      const productNameLines = doc.splitTextToSize(item.productName, labelWidth - 4);
      doc.text(productNameLines, x + labelWidth / 2, topY + 6, { align: 'center' });

      let currentY = topY + 6 + (productNameLines.length * 5);

      // Brand/Model
      if (item.brand || item.model) {
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`${item.brand} ${item.model}`, x + labelWidth / 2, currentY + 4, { align: 'center' });
        currentY += 4;
      }

      // Product No
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Product No: ${item.productNo}`, x + labelWidth / 2, currentY + 4, { align: 'center' });
      currentY += 4;

      // IMEI if present
      if (item.imei) {
        doc.setFontSize(8);
        doc.setTextColor(200, 150, 0);
        doc.text(`IMEI: ${item.imei}`, x + labelWidth / 2, currentY + 4, { align: 'center' });
        currentY += 4;
      }

      // Add barcode image
      const imgData = canvas.toDataURL('image/png');
      doc.addImage(imgData, 'PNG', x + 5, currentY + 2, labelWidth - 10, 15);

      // Type badge
      doc.setFontSize(8);
      doc.setFont(undefined, 'bold');
      if (item.type === 'Mobile') {
        doc.setTextColor(30, 64, 175);
      } else {
        doc.setTextColor(21, 128, 61);
      }
      doc.text(item.type, x + labelWidth / 2, currentY + 20, { align: 'center' });
      doc.setTextColor(0);

      // Move to next position
      labelCount++;
      if (labelCount % 2 === 0) {
        x = margin;
        y += labelHeight + gap;
      } else {
        x += labelWidth + gap;
      }
    }
  }
  return doc;
}

window.BarcodeLabels = { THERMAL_DEFAULTS, THERMAL_LIMITS, thermalSizeError, loadThermalSettings, saveThermalSettings, normalizeScanCode, findScanMatch, resolvePosScan, barcodeValueOf, countModules, planThermalLabel, checkThermalLabels, buildThermalPdf, buildA4Pdf };
})();
